### ISSUE TITLE
Script doesnt work rn

### ISSUE THREAD

**Issue by NaotoEnjoyer** [kousw/stable-diffusion-webui-daam#18]
hey i installed it just a few days ago, and i face this issue, when i do one tag for visualization it just gives me error in cmd listing various script's .pys, if i do multiple tags, it make og pic and a few more with tag on top of the each image but image dont have heatmap and same says cmd no heatmaps for and prompt name

**Comment by NaotoEnjoyer** [comment]
heres error log
Error executing callback before_image_saved_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam_script.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 121, in before_image_saved_callback
    c.callback(params)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam_script.py", line 240, in handle_before_image_saved
    before_image_saved_handler(params)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam_script.py", line 131, in <lambda>
    before_image_saved_handler = lambda params : self.before_image_saved(params)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam_script.py", line 210, in before_image_saved
    img : Image.Image = utils.image_overlay_heat_map(params.image, heat_map_img, alpha=self.alpha, caption=caption, image_scale=self.heatmap_image_scale)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam/utils.py", line 63, in image_overlay_heat_map
    heat_map = _convert_heat_map_colors(heat_map)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam/utils.py", line 86, in _convert_heat_map_colors
    color_map = np.array([ get_color(i) * 255 for i in range(256) ])
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam/utils.py", line 86, in <listcomp>
    color_map = np.array([ get_color(i) * 255 for i in range(256) ])
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-daam-master/scripts/daam/utils.py", line 84, in get_color
    return np.array(cm.turbo(value / 255)[0:3])
AttributeError: module 'matplotlib.cm' has no attribute 'turbo'

**Comment by Havegum** [comment]
PR #19 should fix it 👇

**Comment by NaotoEnjoyer** [comment]
> PR #19 should fix it 👇

hey where do i put these lines? i cant find install.py file
