### ISSUE TITLE
Script run failure with "TypeError: FrozenCLIPEmbedderWithCustomWordsBase [...]" error.

### ISSUE THREAD

**Issue by jasonkoo95** [kousw/stable-diffusion-webui-daam#21]
when running attempting to run the script, it fails with the message:
`TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given`

I've found 3 instances of people discussing this issue in the past 12 hrs:
1) https://boards.4channel.org/g/thread/90766509
2) https://arca.live/b/aiart/67031517/306606102#c_306606102
3) me.

### Steps to regenerate:
1. press generate
2. observe failure:
![image](https://user-images.githubusercontent.com/20150906/211184189-b1ae885a-6918-444b-ab14-584a4fb0d07d.png)

Here's the whole log
```
Error completing request
Arguments: ('', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 4, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, False, '', 1, '', 0, '', True, False, False, '', False, False, False, False, 'Auto', 0.5, 1) {}
Traceback (most recent call last):
  File "F:\webui\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "F:\webui\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "F:\webui\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "F:\webui\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "F:\webui\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 118, in run    prompt_analyzer = utils.PromptAnalyzer(embedder, styled_prompt)
  File "F:\webui\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py", line 274, in __init__
    remade_tokens, fixes, multipliers, token_count = self.tokenize_line(text, used_custom_terms=self.used_custom_terms, hijack_comments=self.hijack_comments)
  File "F:\webui\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py", line 290, in tokenize_line
    remade_tokens, fixes, multipliers, token_count = self.clip.tokenize_line(line, used_custom_terms, hijack_comments)
TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given
```

**Comment by parsec501** [comment]
Same issue here, on a new install

**Comment by jwoeifjofwefawsfasd** [comment]
Going to a previous commit (81133d4168ae0bae9bf8bf1a1d4983319a589112) of WebUI seems to solve this issue. Seems like there's a compatibility issue with the newest commit.

**Comment by dathide** [comment]
This error just showed up for me too
