### ISSUE TITLE
Getting a tokenize_line() error

### ISSUE THREAD

**Issue by adalast** [kousw/stable-diffusion-webui-daam#25]
I am trying to use this and keep running into this error:
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\User\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\Users\User\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 118, in run
    prompt_analyzer = utils.PromptAnalyzer(embedder, styled_prompt)
  File "C:\Users\User\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py", line 274, in __init__
    remade_tokens, fixes, multipliers, token_count = self.tokenize_line(text, used_custom_terms=self.used_custom_terms, hijack_comments=self.hijack_comments)
  File "C:\Users\User\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py", line 290, in tokenize_line
    remade_tokens, fixes, multipliers, token_count = self.clip.tokenize_line(line, used_custom_terms, hijack_comments)
TypeError: tokenize_line() takes 2 positional arguments but 4 were given

**Comment by Pyurah** [comment]
I get the same error.

**Comment by Lordxan** [comment]
I had it fixed by using old commit 56028efbcdec1c4a06d99c0ac19644ede720cdbf but it doesn't work with LoRA

**Comment by FurkanGozukara** [comment]
same error

**Comment by toyxyz** [comment]
same error

**Comment by medledan** [comment]
This extension is completely broken. I have the same error.

**Comment by FurkanGozukara** [comment]
> This extension is completely broken. I have the same error.

Use this one it works for most of the tokens

https://github.com/toriato/stable-diffusion-webui-daam

**Comment by medledan** [comment]
> > This extension is completely broken. I have the same error.
> 
> Use this one it works for most of the tokens
> 
> https://github.com/toriato/stable-diffusion-webui-daam

This extension is working well. Thanks for the suggestion!

**Comment by adalast** [comment]
@medledan what did you do to get it working?  I deactivated the one that was installed using the UI and did a manual add using the link given and it is still throwing the same error.

**Comment by Sequentilian** [comment]
Yet another disgruntled DAAM user here to confirm the same error;
TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given

**Comment by machinesarenotpeople** [comment]
I get TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given

**Comment by guahunyo** [comment]
same error
