### ISSUE TITLE
Missing imports right after installing

### ISSUE THREAD

**Issue by skoot** [kousw/stable-diffusion-webui-daam#28]
I just installed this extension and I get the following error in the console:

```
Error loading script: daam_script.py
Traceback (most recent call last):
  File "K:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 21, in <module>
    from scripts.daam import trace, utils
  File "K:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\__init__.py", line 3, in <module>
    from .utils import *
  File "K:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py", line 9, in <module>
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'
```

I tried doing a pip install fonts but then it says that fonts.ttf doesn't contain Roboto.

And a few lines later I also see a missing dependency on `ldm`

I don't see any `requirements.txt` file in this repo, shouldn't it have one?

**Comment by 1nSaneRu** [comment]
I have this problem too...
After your fix any generation broken

**RuntimeError: shape '[8, 1, 25, 18]' is invalid for input of size 3800**

And other same strings...

**Comment by justarmadillo** [comment]
go to the extension location under: 
stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\

replace utils.py with these 2 files, it should work 100%

[fix.zip](https://github.com/kousw/stable-diffusion-webui-daam/files/12716170/fix.zip)

**Comment by justarmadillo** [comment]
go to the extension location under: 
stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\

replace utils.py with these 2 files, it should work 100%

[fix.zip](https://github.com/kousw/stable-diffusion-webui-daam/files/12716170/fix.zip)
