### ISSUE TITLE
AssertionError: assert(len(merge_idxs) > 0)

### ISSUE THREAD

**Issue by Acruid** [kousw/stable-diffusion-webui-daam#3]
```
venv "C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI


Launching Web UI with arguments: --precision full --no-half --medvram --xformers --listen
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from C:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
daam run
100%|██████████████████████████████████████████████████████████████████████████████████| 80/80 [03:45<00:00,  2.82s/it]
Error executing callback before_image_saved_callback for C:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 121, in before_image_saved_callback
    c.callback(params)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 101, in before_image_saved
    heat_map = utils.expand_image(global_heat_map.compute_word_heat_map(attention), img_size[1], img_size[0])
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\trace.py", line 54, in compute_word_heat_map
    assert(len(merge_idxs) > 0)
AssertionError

Total progress: 100%|██████████████████████████████████████████████████████████████████| 80/80 [03:48<00:00,  2.86s/it]
```
I think it is caused by the prompt box at the top being empty?

**Comment by kousw** [comment]
This may happen if the prompt is empty or has an extra comma.
I'll fix it.

**Comment by kousw** [comment]
Fixed issue with empty prompt.
