### ISSUE TITLE
   RuntimeError: shape '[8, 1, 112, 74]' is invalid for input of size 67800

### ISSUE THREAD

**Issue by karl-tran-2002** [kousw/stable-diffusion-webui-daam#34]
Traceback (most recent call last):
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/img2img.py", line 232, in img2img
        processed = process_images(p)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/processing.py", line 794, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 449, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/processing.py", line 1381, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 434, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 303, in launch_sampling
        return func()
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 434, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 202, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/base/stable-diffusion-v152/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/trace.py", line 41, in _forward
        super_return = hk_self.monkey_super('forward', *args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/hook.py", line 65, in monkey_super
        return self.old_state[f'old_fn_{fn_name}'](*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 874, in forward_webui
        raise e
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 871, in forward_webui
        return forward(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 778, in forward
        h = module(h, emb, context)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 273, in _forward
        x = self.attn2(self.norm2(x), context=context) + x
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/trace.py", line 285, in _forward
        out = hk_self._hooked_attention(self, q, k, v, batch_size, sequence_length, dim)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/trace.py", line 366, in _hooked_attention
        maps = hk_self._up_sample_attn(attn_slice, value, factor)
      File "/base/TuanKhai-Workspace/khai-envs/sd_v152/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/base/stable-diffusion-v152/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/trace.py", line 238, in _up_sample_attn
        map_ = map_.unsqueeze(1).view(map_.size(0), 1, h, w)
    RuntimeError: shape '[8, 1, 112, 74]' is invalid for input of size 67800

**Comment by concertypin** [comment]
possible duplication of #23.
