### ISSUE TITLE
module 'scripts.daam.utils' has no attribute 'escape_prompt'

### ISSUE THREAD

**Issue by some9000** [kousw/stable-diffusion-webui-daam#8]
Well, it doesn't work after the latest update. Not sure why, since the thing it is looking for is inside that file and the file is inside the scripts folder.
```
Traceback (most recent call last):
  File "C:\Users\some9000\Downloads\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\some9000\Downloads\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\some9000\Downloads\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\some9000\Downloads\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "C:\Users\some9000\Downloads\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 101, in run
    tokens = tokenize(utils.escape_prompt(styled_prompt))
AttributeError: module 'scripts.daam.utils' has no attribute 'escape_prompt'
```

**Comment by kousw** [comment]
Have you tried rebooting?
This script seems to have a problem that "Apply and restart UI" alone does not update.

What version of Python do you have?
Even the latest Web UI is working in my environment, so maybe I am writing code that is stuck in some version of Python.

**Comment by some9000** [comment]
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b

I wrote after a third complete restart of Web UI. Now, to try and copy more error messages, started it and it suddenly works. Maybe it's just the Web UI extension install process working weird or such.
