### ISSUE TITLE
Doesn't seem to work if prompt is >75 tokens.  

### ISSUE THREAD

**Issue by winthropharvey** [kousw/stable-diffusion-webui-daam#9]
Traceback (most recent call last):
  File "C:\Users\Wint\Desktop\AIDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 121, in before_image_saved_callback
    c.callback(params)
  File "C:\Users\Wint\Desktop\AIDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 207, in handle_before_image_saved
    before_image_saved_handler(params)
  File "C:\Users\Wint\Desktop\AIDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 108, in <lambda>
    before_image_saved_handler = lambda params : self.before_image_saved(params)
  File "C:\Users\Wint\Desktop\AIDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 162, in before_image_saved
    global_heat_map = self.tracer.compute_global_heat_map(styled_prompot, batch_pos)
  File "C:\Users\Wint\Desktop\AIDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam\trace.py", line 180, in compute_global_heat_map
    maps = torch.stack([torch.stack(x, 0) for x in all_merges], dim=0)
RuntimeError: stack expects a non-empty TensorList

Consistently errors whenever the prompt is more than 75 tokens.

**Comment by kousw** [comment]
Can you see the following outputs?

>daam run with context_size= 154

If the token is less than or equal to 75, context_size is 77.
If the token is greater than 75 (and less than or equal to 150), context_size would be 154.
If the prompt contains strange characters, the number of tokens may not be correctly ascertained, so there is a bug that causes it to be shifted.
(In this case, the attention text will also be shifted, resulting in incorrect results.)

If context_size is 154 and you get the above error, there may be another bug.
Is it possible to share prompts?

**Comment by kousw** [comment]
Thank you for your reporting. I wasn't concerned about embedding, but I'm pretty sure that doesn't work correctly because it expands to multiple tokens.
I'll try to fix it.
